[versions]
agp = "8.10.1"
annotations = "26.0.2"

[libraries]
annotations = { group = "org.jetbrains", name = "annotations", version.ref = "annotations" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }

